# Prepare data from "Gemeinsamer Bundesauschluss" (gBA)
# Parts of this code probably have been generated by generative AI models

rm(list = ls())

# Load libraries
library(readxl)
library(tidyverse)
library(xml2)


# Download files

# Manual download is possible on 
# https://www.g-ba.de/themen/arzneimittel/arzneimittel-richtlinie-anlagen/nutzenbewertung-35a/ais/#direkter-download

# Automatic download link gets invalid after 3 months inactivity
import_file <- "./src/resources/gBA.xml"
download.file(url = "https://ais.g-ba.de/download/1a3faa01-e3f5-41b0-9900-bdeb3a4eec7a"
              , destfile = import_file
              , method = "libcurl"
              , mode="wb")


# Prepare data

# Function to extract data from XML
extract_gba_info <- function(xml_path) {
  doc <- read_xml(xml_path)
  
  # Find all BE Nodes
  nodes <- xml_find_all(doc, ".//BE")
  
  be_result <- lapply(nodes, function(be){
    
    name_hn <- xml_attr(xml_find_first(be, ".//ZUL/NAME_HN"), "value")

    # Find all ID_PAT_GR nodes
    pat_nodes <- xml_find_all(be, ".//ID_PAT_GR")
    
    # For each ID_PAT_GR, extract the required info
    pat_result <- lapply(pat_nodes, function(pat) {
      
      id_pat_gr <- xml_attr(pat, "value")
      ws_bew <- xml_attr(xml_find_first(pat, ".//WS_BEW/NAME_WS_BEW"), "value")
      atc_fix_komb <- xml_attr(xml_find_first(pat, ".//WS_BEW/ATC_WS_FIX_KOMB"), "value")
      atc_code <- xml_attr(xml_find_first(pat, ".//WS_INFO_BEW/ATC/ATC_CODE"), "value")

      # Find all ICD nodes
      icd_nodes <- xml_find_all(pat, ".//ICD")

      # For each ICD, extract the required info
      icd_result <- lapply(icd_nodes, function(icd){
        id_icd <- xml_attr(xml_find_first(icd, "./ID_ICD"), "value")
        name_icd <- xml_attr(xml_find_first(icd, "./NAME_ICD"), "value")

        data.frame(
          NAME_HN = name_hn,
          ID_PAT_GR = id_pat_gr,
          WS_BEW = ws_bew,
          ATC_FIX_KOMB = atc_fix_komb,
          ATC_CODE = atc_code,
          ID_ICD = id_icd,
          NAME_ICD = name_icd,
          stringsAsFactors = FALSE)

      })
      bind_rows(icd_result)
    })
    
    bind_rows(pat_result)
  })
  bind_rows(be_result)

}

# Apply function to dataset
df_gBA <- extract_gba_info("./src/resources/gBA.xml")
df_gBA$ATC <- ifelse(is.na(df_gBA$ATC_CODE), df_gBA$ATC_FIX_KOMB, df_gBA$ATC_CODE)

gBA <- df_gBA %>% 
  select(-ATC_FIX_KOMB, -ATC_CODE, -ID_PAT_GR) %>%
  unique()

# Change some of the detailed IDC-10 codes to higher code level

# show codes
gBA %>% 
  group_by(substr(ID_ICD,1,3)) %>% 
  summarise(anz=n()) %>% 
  arrange(desc(anz)) %>% 
  filter(anz > 20) %>%
  print(n=100)

# change codes (group/aggregate them)
gBA <- gBA %>%
  mutate(ID_ICD_GROUPED = case_when(
    substr(ID_ICD,1,3) %in% 
      c('C18','C16','C34','C43','C50','C67','E11','E12','E13','E14','E84','M05','M06','J44') ~ 
      substr(ID_ICD,1,3),
    .default = ID_ICD
  ),
  NAME_ICD_GROUPED = case_when(
    substr(ID_ICD,1,3) == 'C18' ~ 'Bösartige Neubildung des Kolons',
    substr(ID_ICD,1,3) == 'C18' ~ 'Bösartige Neubildung des Magens',
    substr(ID_ICD,1,3) == 'C34' ~ 'Bösartige Neubildung der Bronchien und der Lunge',
    substr(ID_ICD,1,3) == 'C43' ~ 'Bösartiges Melanom der Haut',
    substr(ID_ICD,1,3) == 'C50' ~ 'Bösartige Neubildung der Brustdrüse [Mamma]',
    substr(ID_ICD,1,3) == 'C67' ~ 'Bösartige Neubildung der Harnblase',
    substr(ID_ICD,1,3) == 'E11' ~ 'Diabetes mellitus',
    substr(ID_ICD,1,3) == 'E12' ~ 'Diabetes mellitus',
    substr(ID_ICD,1,3) == 'E13' ~ 'Diabetes mellitus',
    substr(ID_ICD,1,3) == 'E14' ~ 'Diabetes mellitus',
    substr(ID_ICD,1,3) == 'E84' ~ 'Zystische Fibrose',
    substr(ID_ICD,1,3) == 'M05' ~ 'Chronische Polyarthritis',
    substr(ID_ICD,1,3) == 'M06' ~ 'Chronische Polyarthritis',
    substr(ID_ICD,1,3) == 'J44' ~ 'Sonstige chronische obstruktive Lungenkrankheit',
    .default = NAME_ICD
  )
  ) %>% 
  unique()


# Export as csv (to import folder of Neo4j)
import_folder <- "./src/main/import"
write.table(gBA, file = paste0(import_folder, "/gBA_icd.csv")
            , row.names = FALSE, sep ="|", fileEncoding = "UTF-8")

# Delete resource file
file.remove(import_file)

