# Prepare data from "Technisches Begleitblatt" for mappings to VA, ZA, Unit
# Parts of this code probably have been generated by generative AI models

rm(list = ls())

# Load libraries
library(readxl)
library(tidyverse)


# Download files
import_file <- "./src/resources/Technisches_Begleitblatt_2025.xlsx"
download.file(url = "https://www.swissdrg.org/download_file/view/5010/2253"
              , destfile = import_file
              , method = "libcurl"
              , mode="wb")


# Import data to environment
import_tech_de <- read_excel(import_file, sheet = 1, skip = 7, col_names = TRUE)
import_tech_fr <- read_excel(import_file, sheet = 2, skip = 7, col_names = TRUE)
import_tech_it <- read_excel(import_file, sheet = 3, skip = 7, col_names = TRUE)

import_tech_de$sprache <- "de"
import_tech_fr$sprache <- "fr"
import_tech_it$sprache <- "it"


# Prepare data
cn <- tolower(colnames(import_tech_de))
cn <- gsub("ä", "ae", gsub("ü", "ue", cn))
cn <- gsub("[^a-zA-Z0-9_]+", "_", cn)
colnames(import_tech_de) <- cn
colnames(import_tech_fr) <- colnames(import_tech_de)
colnames(import_tech_it) <- colnames(import_tech_de)

technisches_begleitblatt <- bind_rows(import_tech_de, import_tech_fr, import_tech_it)
technisches_begleitblatt <- fill(technisches_begleitblatt,variablenname)

technisches_begleitblatt <- technisches_begleitblatt %>% 
  select(sprache, variablenname, kuerzel, kuerzel_bezeichnung, hinweis)

technisches_begleitblatt$hinweis <- gsub("\n", "", technisches_begleitblatt$hinweis)


# Export as csv (to import folder of Neo4j)
import_folder <- "./src/main/import"
write.csv(technisches_begleitblatt
    , file = paste0(import_folder,"/technisches_begleitblatt.csv")
    , row.names = FALSE)


# Delete resource file
file.remove(import_file)
