# Import data from European Medicines Agency (EMA) and group indication per ATC Code
# Parts of this code probably have been generated by generative AI models

rm(list = ls())

# Load libraries
library(readxl)
library(tidyverse)


# Download files
ema_file <- "./src/resources/medicines_output_medicines_report_en.xlsx"
download.file(url = "https://www.ema.europa.eu/en/documents/report/medicines-output-medicines-report_en.xlsx"
            , destfile = ema_file
            , method = "libcurl"
            , mode = "wb")


# Import data to environment
dateOfData <- read_excel(ema_file, range = "D1:D1", col_names = c("dateOfData"))
medicines_output_medicines_report_en <- read_excel(ema_file, skip = 8)


# Filter and arrange data (only authorised medicines --> is this useful??)
ema_data <- medicines_output_medicines_report_en %>% 
  filter(`Medicine status` == "Authorised", Category == "Human") %>%
  select(`ATC code (human)`, `Therapeutic area (MeSH)`,`Active substance`
        ,`Name of medicine`,`Therapeutic indication`,`Orphan medicine`, `Generic or hybrid`, Biosimilar,
        ,`Marketing authorisation developer / applicant / holder`,`Medicine URL`) %>% 
  unique()
names(ema_data) <- c("atc","mesh","substance","product_name","indication","orphan","generic","biosimilar","company","url")


# update atc-codes which are not correct
ema_data[ema_data$product_name=='Cyramza','atc'] <-"L01FG02"
ema_data[ema_data$product_name=='Trodelvy','atc'] <-"L01FX17"
ema_data[ema_data$product_name=='Besponsa','atc'] <-"L01FB01"
ema_data[ema_data$product_name=='Vumerity','atc'] <-"L04AX09"


# Export as csv (to import folder of Neo4j)
import_folder <- "./src/main/import"
#import_folder <- "C:/Users/chris/.Neo4jDesktop/relate-data/dbmss/dbms-1b22f9fd-60d2-456a-9552-ae44cb5352d7/import"
#import_folder <- "C:/Users/chris/Desktop/Aura DB csv load/medi_graph"
write.table(ema_data
    , file = paste0(import_folder,"/ema_products.csv")
    , row.names = FALSE, quote = TRUE, sep = "|")


# Delete resource file
file.remove(ema_file)
