# "Präparate" data from Refdata (SAI)
# Parts of this code probably have been generated by generative AI models

rm(list = ls())

# Load libraries
library(xml2)
library(dplyr)
library(stringr)


# Download files
sai_file <- "./src/resources/sai.zip"
download.file(url = "https://sai.refdata.ch/download/structuredexportzip/8480"
              , destfile = sai_file
              , method = "libcurl"
              , mode="wb")
unzip(sai_file, exdir = "./src/resources/", list=TRUE)
unzip(sai_file, exdir = "./src/resources/"
  , files = c("SAI/SAI-Praeparate.XML", "SAI/SAI-Adressen.XML"))


# Parse the XML file
xml_file <- read_xml("./src/resources/SAI/SAI-Praeparate.XML")

# Define the XML namespace
ns <- c(ns1 = "http://sai.refdata.ch")

# Extract PRAEPARAT elements without 'nicht mehr zugelassen'
praeparate <- xml_find_all(xml_file, paste0(".//ns1:PRAEPARAT[ns1:ZULASSUNGSSTATUS/text()!='D']"), ns)

# Initialize an empty data frame
data <- data.frame(
  VERWENDUNG = character(),
  ZULASSUNGSNUMMER = character(),
  PRAEPARATENAME = character(),
  ARZNEIFORM = character(),
  ATC_CODE = character(),
  HEILMITTEL_CODE = character(),
  ZULASSUNGSSTATUS = character(),
  ZULASSUNGSKATEGORIE = character(),
  ZULASSUNGSINHABERIN = character(),
  ERSTZULASSUNGSDATUM = character(),
  BASIS_ZULASSUNGSNUMMER = character(),
  ABGABEKATEGORIE = character(),
  IT_NUMMER = character(),
  ANWENDUNGSGEBIET = character(),
  ABLAUFDATUM = character(),
  CHARGENFREIGABE_PFLICHT = character(),
  EINZELEINFUHR_BEWILLIG_PFLICHT = character(),
  stringsAsFactors = FALSE
)

# Iterate over each PRAEPARAT element and extract child elements
for (praep in praeparate) {
  row <- data.frame(
    VERWENDUNG = xml_text(xml_find_first(praep, "ns1:VERWENDUNG", ns)),
    ZULASSUNGSNUMMER = xml_text(xml_find_first(praep, "ns1:ZULASSUNGSNUMMER", ns)),
    PRAEPARATENAME = xml_text(xml_find_first(praep, "ns1:PRAEPARATENAME", ns)),
    ARZNEIFORM = xml_text(xml_find_first(praep, "ns1:ARZNEIFORM", ns)),
    ATC_CODE = xml_text(xml_find_first(praep, "ns1:ATC_CODE", ns)),
    HEILMITTEL_CODE = xml_text(xml_find_first(praep, "ns1:HEILMITTEL_CODE", ns)),
    ZULASSUNGSSTATUS = xml_text(xml_find_first(praep, "ns1:ZULASSUNGSSTATUS", ns)),
    ZULASSUNGSKATEGORIE = xml_text(xml_find_first(praep, "ns1:ZULASSUNGSKATEGORIE", ns)),
    ZULASSUNGSINHABERIN = xml_text(xml_find_first(praep, "ns1:ZULASSUNGSINHABERIN", ns)),
    ERSTZULASSUNGSDATUM = xml_text(xml_find_first(praep, "ns1:ERSTZULASSUNGSDATUM", ns)),
    BASIS_ZULASSUNGSNUMMER = xml_text(xml_find_first(praep, "ns1:BASIS_ZULASSUNGSNUMMER", ns)),
    ABGABEKATEGORIE = xml_text(xml_find_first(praep, "ns1:ABGABEKATEGORIE", ns)),
    IT_NUMMER = xml_text(xml_find_first(praep, "ns1:IT_NUMMER", ns)),
    ANWENDUNGSGEBIET = xml_text(xml_find_first(praep, "ns1:ANWENDUNGSGEBIET", ns)),
    ABLAUFDATUM = xml_text(xml_find_first(praep, "ns1:ABLAUFDATUM", ns)),
    CHARGENFREIGABE_PFLICHT = xml_text(xml_find_first(praep, "ns1:CHARGENFREIGABE_PFLICHT", ns)),
    EINZELEINFUHR_BEWILLIG_PFLICHT = xml_text(xml_find_first(praep, "ns1:EINZELEINFUHR_BEWILLIG_PFLICHT", ns)),
    stringsAsFactors = FALSE
  )
  data <- bind_rows(data, row)
}

df_praeparate <- data

# Update ATC (Refdata is not "super" updated at all -> Compendium seem to have the "best" data)
df_praeparate[df_praeparate$ZULASSUNGSNUMMER=='67575',"ATC_CODE"]<-'L01XL07'
df_praeparate[df_praeparate$ZULASSUNGSNUMMER=='68844',"ATC_CODE"]<-'B02BX10'
df_praeparate[df_praeparate$ZULASSUNGSNUMMER=='67469',"ATC_CODE"]<-'L01XL08'
df_praeparate[df_praeparate$ZULASSUNGSNUMMER=='68297',"ATC_CODE"]<-'L01FX28'
df_praeparate[df_praeparate$ZULASSUNGSNUMMER=='68646',"ATC_CODE"]<-'L01FX32'
df_praeparate[df_praeparate$ZULASSUNGSNUMMER=='65920',"ATC_CODE"]<-'L01FX08'
df_praeparate[df_praeparate$ZULASSUNGSNUMMER=='68147',"ATC_CODE"]<-'L01EB10'
df_praeparate[df_praeparate$ZULASSUNGSNUMMER=='69556',"ATC_CODE"]<-'B02BX11'
df_praeparate[df_praeparate$ZULASSUNGSNUMMER=='68733',"ATC_CODE"]<-'L01EL05'
df_praeparate[df_praeparate$ZULASSUNGSNUMMER=='67758',"ATC_CODE"]<-'L04AG12'
df_praeparate[df_praeparate$ZULASSUNGSNUMMER=='67757',"ATC_CODE"]<-'L04AG12'
df_praeparate[df_praeparate$ZULASSUNGSNUMMER=='63025',"ATC_CODE"]<-'L04AG06'
df_praeparate[df_praeparate$ZULASSUNGSNUMMER=='67230',"ATC_CODE"]<-'L04AE03'
df_praeparate[df_praeparate$ZULASSUNGSNUMMER=='68951',"ATC_CODE"]<-'L04AC24'
df_praeparate[df_praeparate$ZULASSUNGSNUMMER=='68952',"ATC_CODE"]<-'L04AC24'
df_praeparate[df_praeparate$ZULASSUNGSNUMMER=='68950',"ATC_CODE"]<-'L04AC24'
df_praeparate[df_praeparate$ZULASSUNGSNUMMER=='69610',"ATC_CODE"]<-'N07XX25'
df_praeparate[df_praeparate$ZULASSUNGSNUMMER=='66495',"ATC_CODE"]<-'M09AX07'
df_praeparate[df_praeparate$ZULASSUNGSNUMMER=='69049',"ATC_CODE"]<-'L01FX29'
df_praeparate[df_praeparate$ZULASSUNGSNUMMER=='69077',"ATC_CODE"]<-'L01XM02'
df_praeparate[df_praeparate$ZULASSUNGSNUMMER=='67278',"ATC_CODE"]<-'L04AJ02'
df_praeparate[df_praeparate$ZULASSUNGSNUMMER=='66344',"ATC_CODE"]<-'J06BC03'

df_praeparate <- df_praeparate%>% 
  filter(ATC_CODE!="",
         VERWENDUNG=="HAM") %>% 
  mutate(ZULASSUNGSNUMMER = as.integer(ZULASSUNGSNUMMER),
         ZULASSUNGSINHABERIN = as.integer(ZULASSUNGSINHABERIN),
         ERSTZULASSUNGSDATUM = as.Date(ERSTZULASSUNGSDATUM),
         ABLAUFDATUM = as.Date(ABLAUFDATUM),
         VERWENDUNG = NULL,
         Praep_Name = tolower(str_split_fixed(PRAEPARATENAME,",",2)[,1]))


# Multiple products have same name, but different ZULASSUNGSNUMMER, Indikation, etc.
df_multiple_produrcts <- df_praeparate %>%
  group_by(Praep_Name) %>%
  summarise(anz=n()) %>%
  arrange(desc(anz)) %>% 
  filter(anz>1)

df_praeparate <- df_praeparate %>% 
  left_join(df_multiple_produrcts,by = join_by("Praep_Name"))


# Add Name of 'ZULASSUNGSINHABERIN" from adress xml-file
xml_file <- read_xml("./src/resources/SAI/SAI-Adressen.XML")
adressen <- xml_find_all(xml_file, paste0(".//ns1:ADRESSE"), ns)

df_adressen <- data.frame(
  PARTNER_NR = as.integer(xml_text(xml_find_first(adressen, "ns1:PARTNER_NR", ns))),
  FIRMENNAME = xml_text(xml_find_first(adressen, "ns1:FIRMENNAME", ns)),
  stringsAsFactors = FALSE
)

df_praeparate <- df_praeparate %>% 
  left_join(df_adressen,by = join_by("ZULASSUNGSINHABERIN"=="PARTNER_NR")) %>% 
  mutate(ZULASSUNGSINHABERIN = NULL)

colnames(df_praeparate) <- sub("FIRMENNAME","ZULASSUNGSINHABERIN",colnames(df_praeparate))


# Export as csv (to import folder of Neo4j)
import_folder <- "./src/main/import"
write.csv(df_praeparate
  , paste0(import_folder,"/sai_praeparate.csv")
  , row.names = FALSE)


# Delete resource file
file.remove(sai_file)
