# Prepare data from "Gemeinsamer Bundesauschluss" (gBA)
# Parts of this code probably have been generated by generative AI models

rm(list = ls())

# Load libraries
library(readxl)
library(tidyverse)
library(xml2)


# Download files

# Manual download is possible on 
# https://www.g-ba.de/themen/arzneimittel/arzneimittel-richtlinie-anlagen/nutzenbewertung-35a/ais/#direkter-download

# Automatic download link gets invalid after 3 months inactivity
import_file <- "./src/resources/gBA.xml"
download.file(url = "https://ais.g-ba.de/download/1a3faa01-e3f5-41b0-9900-bdeb3a4eec7a"
              , destfile = import_file
              , method = "libcurl"
              , mode="wb")


# Prepare data

# Function to extract data from XML
extract_gba_info <- function(xml_path) {
  doc <- read_xml(xml_path)
  
  # Find all BE Nodes
  nodes <- xml_find_all(doc, ".//BE")
  
  be_result <- lapply(nodes, function(be){
    
    id_be <- xml_attr(xml_find_first(be, ".//ID_BE"), "value")
    url <- xml_attr(xml_find_first(be, ".//URL"), "value")
    name_hn <- xml_attr(xml_find_first(be, ".//ZUL/NAME_HN"), "value")

    # Find all ID_PAT_GR nodes
    pat_nodes <- xml_find_all(be, ".//ID_PAT_GR")
    
    # For each ID_PAT_GR, extract the required info
    pat_result <- lapply(pat_nodes, function(pat) {
      
      id_pat_gr <- xml_attr(pat, "value")
      ws_bew <- xml_attr(xml_find_first(pat, ".//WS_BEW/NAME_WS_BEW"), "value")
      atc_fix_komb <- xml_attr(xml_find_first(pat, ".//WS_BEW/ATC_WS_FIX_KOMB"), "value")
      atc_code <- xml_attr(xml_find_first(pat, ".//WS_INFO_BEW/ATC/ATC_CODE"), "value")
      datum_be_vom <- xml_attr(xml_find_first(pat, ".//DATUM_BE_VOM"), "value")
      name_zvt_best <- xml_attr(xml_find_first(pat, ".//ZVT_BEST/NAME_ZVT_BEST"), "value")
      zvt_zn_a <- xml_attr(xml_find_first(pat, ".//ZVT_ZN/ZN_A"), "value")
      zvt_zn_w <- xml_attr(xml_find_first(pat, ".//ZVT_ZN/ZN_W"), "value")
      data.frame(
        ID_BE = id_be,
        URL = url,
        NAME_HN = name_hn,
        ID_PAT_GR = id_pat_gr,
        WS_BEW = ws_bew,
        ATC_FIX_KOMB = atc_fix_komb,
        ATC_CODE = atc_code,
        DATUM_BE_VOM = datum_be_vom,
        NAME_ZVT_BEST = name_zvt_best,
        ZVT_ZN_A = zvt_zn_a,
        ZVT_ZN_W = zvt_zn_w,
        stringsAsFactors = FALSE
      )
    })
    
    bind_rows(pat_result)
  }
  )
  bind_rows(be_result)

}

# Apply function to dataset
df_gBA <- extract_gba_info("./src/resources/gBA.xml")
df_gBA$ATC <- ifelse(is.na(df_gBA$ATC_CODE), df_gBA$ATC_FIX_KOMB, df_gBA$ATC_CODE)

gBA <- df_gBA %>% 
  select(-ATC_FIX_KOMB, -ATC_CODE)

# Export as csv (to import folder of Neo4j)
import_folder <- "./src/main/import"
write.table(gBA, file = paste0(import_folder, "/gBA_nutzenbewertung.csv")
            , row.names = FALSE, sep ="|", fileEncoding = "UTF-8")

# Delete resource file
file.remove(import_file)

