# Prepare data for supplemtents (Zusatzentgelte) for all tariff types
# Parts of this code probably have been generated by generative AI models

rm(list = ls())

# Load libraries
library(readr)
library(tidyverse)


# Import data to environment
definitions <- read_delim("./src/1 bronze/staging area/definitions.csv", 
                            delim = "|", escape_double = FALSE, trim_ws = TRUE)

# data for reha + tarpsy (here manually prepared, in SwissDRG via API)
ze_tr <- read_delim("./src/1 bronze/staging area/ZE_tarpsy_reha.csv", 
                            delim = "|", escape_double = FALSE, trim_ws = TRUE)


# Prepare data
definitions$ze_code <- str_split_i(definitions$ze, "[.]",1)
definitions$ze_nr <-as.numeric(str_split_i(definitions$ze_code, "[-]",3))

ze_akut <- definitions %>% 
  filter(type=="A") %>% 
  select(ze_nr,ze_code,version,code,dose_unit,va,za) %>% 
  unique()

ze_all <- rbind(ze_akut,ze_tr)
ze_all$ze_id <- gsub("-[0-9]{4}-","-", ze_all$ze_code)


# Export as csv
silver_folder <- "./src/2 silver/staging area/"
write.table(ze_all
  , file = paste0(silver_folder, "ze_definitions.csv")
  , row.names = FALSE, sep ="|", fileEncoding = "UTF-8")

