# Import data from European Medicines Agency (EMA) and group indication per ATC Code
# Parts of this code probably have been generated by generative AI models

rm(list = ls())

# Load libraries
library(readxl)
library(tidyverse)

bronze_file <- "./src/1 bronze/staging area/medicines_output_medicines_report_en.xlsx"

# Import data to environment
dateOfData <- read_excel(bronze_file, range = "D1:D1", col_names = c("dateOfData"))
medicines_output_medicines_report_en <- read_excel(bronze_file, skip = 8)


# Filter and arrange data
ema_data <- medicines_output_medicines_report_en %>% 
  filter(Category == "Human", `Medicine status` == "Authorised" |
           (`Medicine status` == "Opinion" & `Opinion status` == "Positive")) %>%
  select(`ATC code (human)`, `Therapeutic area (MeSH)`,`Active substance`
        ,`Name of medicine`,`Therapeutic indication`,`Orphan medicine`, `Generic`, Biosimilar
        ,`Marketing authorisation developer / applicant / holder`,`Medicine URL`) %>% 
  unique()
names(ema_data) <- c("atc","mesh","substance","product_name","indication","orphan","generic","biosimilar","company","url")


# update atc-codes which are not correct
ema_data[ema_data$product_name=='Cyramza','atc'] <-"L01FG02"
ema_data[ema_data$product_name=='Trodelvy','atc'] <-"L01FX17"
ema_data[ema_data$product_name=='Besponsa','atc'] <-"L01FB01"
ema_data[ema_data$product_name=='Vumerity','atc'] <-"L04AX09"
ema_data[ema_data$product_name=='Pedmarqsi','atc'] <-"V03AB06"
ema_data[ema_data$product_name=='Itovebi','atc'] <-"L01EM06"


# Export as csv
silver_folder <- "./src/2 silver/staging area/"
write.table(ema_data
    , file = paste0(silver_folder,"/ema_products.csv")
    , row.names = FALSE, quote = TRUE, sep = "|")


# Delete bronze file
file.remove(bronze_file)
