# Prepare data of "Spezialitätenliste" from BAG
# Parts of this code probably have been generated by generative AI models

rm(list = ls())

# Load libraries
library(readxl)
library(janitor)


# Import data to environment
bronze_file <- "./src/1 bronze/staging area/Publications.xlsx"
Publications <- read_excel(bronze_file, 
                           sheet = "Publications")
colnames(Publications) <- sub(" per.*", "", colnames(Publications))
Publications <- clean_names(Publications)


# Prepare data
Publications$zulassungsnummer <- floor(as.numeric(Publications$swissmedic_nr)/1000)
Publications$zulassungsnummer <- as.character(Publications$zulassungsnummer)

Publications$letzte_preis_anderung <- as.Date(
  ifelse(!is.na(Publications$letzte_preis_anderung),
         Publications$letzte_preis_anderung,
         Publications$einf_datum),
  "%d.%m.%Y")
Publications$einf_datum <- as.Date(Publications$einf_datum, "%d.%m.%Y")


# Export as csv
silver_folder <- "./src/2 silver/staging area/"
write.table(Publications, file = paste0(silver_folder, "/sl.csv")
            , row.names = FALSE, sep ="|", fileEncoding = "UTF-8")


# Delete bronze file
file.remove(bronze_file)
